apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-demo-component-gmsq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/bootstrap/rhtap-demo-dev-mjaq-tenant/mvp-test-app/rhtap-demo-component-gmsq@sha256:7bd649d52d0dd3d68a1422263e2ad5b3873ded7b02a2baf75f8be6a39d1f06fc
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
